apiVersion: v1
kind: Service
metadata:
  name: edgex-device-rest
spec:
  selector:
    app: edgex-device-rest
  type: ClusterIP
  ports:
    - name: device-rest-port
      port: 59986
      targetPort: 59986
      protocol: TCP

