apiVersion: v1
kind: Service
metadata:
  name: edgex-core-command
spec:
  selector:
    app: edgex-core-command
  type: ClusterIP
  ports:
    - name: "59882"
      port: 59882
      targetPort: 59882
