apiVersion: v1
kind: Service
metadata:
  name: edgex-redis
  namespace: default
spec:
  selector:
    app: edgex-redis
  type: ClusterIP
  ports:
    - name: redis-port
      port: 6379
      targetPort: 6379
      protocol: TCP