apiVersion: v1
kind: Service
metadata:
  name: edgex-support-notifications
spec:
  selector:
    app: edgex-support-notifications
  ports:
    - name: support-notification-port
      port: 59860
      targetPort: 59860
