apiVersion: v1
kind: Service
metadata:
  name: edgex-app-service-rules
spec:
  selector:
    app: edgex-app-service-rules
  type: ClusterIP
  ports:
    - name: app-service-port
      port: 59701
      targetPort: 59701
      protocol: TCP
