apiVersion: apps/v1
kind: Deployment
metadata:
  name: edgex-core-consul
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edgex-core-consul
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: edgex-core-consul
    spec:
      containers:
        - image: consul:1.9.5
          name: edgex-core-consul
          ports:
            - containerPort: 8500
              protocol: TCP 
          volumeMounts:
            - mountPath: /consul/config
              name: consul-config
            - mountPath: /consul/data
              name: consul-data
      restartPolicy: Always
      volumes:
        - name: consul-config
          persistentVolumeClaim:
            claimName: consul-config
        - name: consul-data
          persistentVolumeClaim:
            claimName: consul-data