apiVersion: v1
kind: Service
metadata:
  name: edgex-core-consul
spec:
  selector:
    app: edgex-core-consul
  ports:
    - name: consul-port
      port: 8500
      targetPort: 8500
      protocol: TCP