apiVersion: v1
kind: Service
metadata:
  name: edgex-device-modbus
spec:
  selector:
    app: edgex-device-modbus
  type: ClusterIP
  ports:
    - name: edgex-device-modbus
      port: 59901
      targetPort: 59901
      protocol: TCP
