apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: edgex-nginx-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: ""
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
                  service:
                      name: edgex-ui-go
                      port:
                        number: 4000
