apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: edgex-nginx-ingress
spec:
  rules:
    - host: ""
      http:
        paths:
          - path: /edgex
            pathType: Prefix
            backend:
                  service:
                      name: edgex-ui-go
                      port:
                        number: 4000