apiVersion: apps/v1
kind: Deployment
metadata:
  name: edgex-kuiper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edgex-kuiper
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: edgex-kuiper
    spec:
      containers:
        - env:
            - name: EDGEX__DEFAULT__PORT
              value: "6379"
            - name: EDGEX__DEFAULT__PROTOCOL
              value: redis
            - name: EDGEX__DEFAULT__SERVER
              value: edgex-redis
            - name: EDGEX__DEFAULT__TOPIC
              value: rules-events
            - name: EDGEX__DEFAULT__TYPE
              value: redis
            - name: KUIPER__BASIC__CONSOLELOG
              value: "true"
            - name: KUIPER__BASIC__RESTPORT
              value: "59720"
          image: lfedge/ekuiper:1.3.0-alpine
          name: edgex-kuiper
          ports:
            - containerPort: 59720
          volumeMounts:
            - mountPath: /kuiper/data
              name: kuiper-data
      restartPolicy: Always
      volumes:
        - name: kuiper-data
          persistentVolumeClaim:
            claimName: kuiper-data