apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: edgex-ui-go
  name: edgex-ui-go
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: edgex-ui-go
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/edgex-network: "true"
        io.kompose.service: edgex-ui-go
    spec:
      containers:
          - name: edgex-ui-go
            image: edgexfoundry/edgex-ui:2.0.0
            imagePullPolicy: IfNotPresent
            ports:
            - name: http
              protocol: TCP
              containerPort: 4000
      hostname: edgex-ui-go
      restartPolicy: Always
status: {}
