apiVersion: v1
kind: Service
metadata:
  name: edgex-ui-go
spec:
  type: NodePort
  selector:
    app: edgex-ui-go
  ports:
      - name: http
        port: 4000
        protocol: TCP
        targetPort: 4000
        nodePort: 30040